#Today's problem involves analyzing car data. This dataset comprises 1728 rows and 6 different attributes: buying price, price of maintenance, number of doors, capacity in terms of persons to carry, the relative size of the luggage boot, and the estimated safety value of each car.
#The Problem: You are tasked with constructing and evaluating a decision tree classifier on this dataset. Utilize and compare different types of split criteria (entropy, Gini index, loss). The decision tree will classify the type of car into one of the following categories: 1) unacceptable, 2) acceptable, 3) good, or 4) very good.

#In addition to developing an ML model, you also need to visualize a trees based on your developed models. The tree can be visualized using graphviz library.

#Note - This time, the data is split into several CSV files and stored in a zipped folder. You need to merge or concatenate the data after reading from multiple files.
#Resource for combining dataframes:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html

#Resources for drawing a tree using Graphviz:

https://scikit-learn.org/stable/modules/generated/sklearn.tree.export_graphviz.html

https://canvas.anglia.ac.uk/files/4155049/download?download_frd=1



In [1]:
################################################################################
#
#
# Your code to develop a decision tree classifier.
# Check the accuracy, performance metrices, and confusion metrics.
# Draw the decision tree using Graphviz.
# You can split your code into different cells according to your own choice
#
#

################################################################################


In [2]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
from IPython.display import Image 
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
import graphviz
try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO
import pydotplus
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier, export_graphviz
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df1 = pd.read_csv('car_evaluation/car_evaluation_0.csv')
df1.tail()

buyPrice maintCost noDoors noPersons bootLuggage safety decision
427    vhigh       low   5more      more         med   high      acc
428    vhigh       low   5more      more         big    low    unacc
429    vhigh       low   5more      more         big    med      acc
430    vhigh       low   5more      more         big   high      acc
431     high     vhigh       2         2       small    low    unacc

In [4]:
df2 = pd.read_csv('car_evaluation/car_evaluation_1.csv')
df2.tail()

buyPrice maintCost noDoors noPersons bootLuggage safety decision
427     high       low   5more      more         med   high      acc
428     high       low   5more      more         big    low    unacc
429     high       low   5more      more         big    med      acc
430     high       low   5more      more         big   high      acc
431      med     vhigh       2         2       small    low    unacc

In [5]:
df3 = pd.read_csv('car_evaluation/car_evaluation_2.csv')
df3.tail()

buyPrice maintCost noDoors noPersons bootLuggage safety decision
427      med       low   5more      more         med   high    vgood
428      med       low   5more      more         big    low    unacc
429      med       low   5more      more         big    med     good
430      med       low   5more      more         big   high    vgood
431      low     vhigh       2         2       small    low    unacc

In [6]:
df4 = pd.read_csv('car_evaluation/car_evaluation_3.csv')
df4.tail()

buyPrice maintCost noDoors noPersons bootLuggage safety decision
426      low       low   5more      more         med    med     good
427      low       low   5more      more         med   high    vgood
428      low       low   5more      more         big    low    unacc
429      low       low   5more      more         big    med     good
430      low       low   5more      more         big   high    vgood

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 432 entries, 0 to 431
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   buyPrice     432 non-null    object
 1   maintCost    432 non-null    object
 2   noDoors      432 non-null    object
 3   noPersons    432 non-null    object
 4   bootLuggage  432 non-null    object
 5   safety       432 non-null    object
 6   decision     432 non-null    object
dtypes: object(7)
memory usage: 23.8+ KB


In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 432 entries, 0 to 431
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   buyPrice     432 non-null    object
 1   maintCost    432 non-null    object
 2   noDoors      432 non-null    object
 3   noPersons    432 non-null    object
 4   bootLuggage  432 non-null    object
 5   safety       432 non-null    object
 6   decision     432 non-null    object
dtypes: object(7)
memory usage: 23.8+ KB


In [9]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 432 entries, 0 to 431
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   buyPrice     432 non-null    object
 1   maintCost    432 non-null    object
 2   noDoors      432 non-null    object
 3   noPersons    432 non-null    object
 4   bootLuggage  432 non-null    object
 5   safety       432 non-null    object
 6   decision     432 non-null    object
dtypes: object(7)
memory usage: 23.8+ KB


In [10]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 431 entries, 0 to 430
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   buyPrice     431 non-null    object
 1   maintCost    431 non-null    object
 2   noDoors      431 non-null    object
 3   noPersons    431 non-null    object
 4   bootLuggage  431 non-null    object
 5   safety       431 non-null    object
 6   decision     431 non-null    object
dtypes: object(7)
memory usage: 23.7+ KB


In [11]:
df = pd.concat([df1, df2, df3, df4], ignore_index=0)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1727 entries, 0 to 430
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   buyPrice     1727 non-null   object
 1   maintCost    1727 non-null   object
 2   noDoors      1727 non-null   object
 3   noPersons    1727 non-null   object
 4   bootLuggage  1727 non-null   object
 5   safety       1727 non-null   object
 6   decision     1727 non-null   object
dtypes: object(7)
memory usage: 107.9+ KB


In [13]:
df['buyPrice'].value_counts()

high     432
med      432
low      432
vhigh    431
Name: buyPrice, dtype: int64

In [14]:
df['maintCost'].value_counts()

high     432
med      432
low      432
vhigh    431
Name: maintCost, dtype: int64

In [15]:
df['noDoors'].value_counts()

3        432
4        432
5more    432
2        431
Name: noDoors, dtype: int64

In [16]:
df['noPersons'].value_counts()

4       576
more    576
2       575
Name: noPersons, dtype: int64

In [17]:
df['bootLuggage'].value_counts()

med      576
big      576
small    575
Name: bootLuggage, dtype: int64

In [18]:
df['safety'].value_counts()

med     576
high    576
low     575
Name: safety, dtype: int64

In [19]:
df['decision'].value_counts()

unacc    1209
acc       384
good       69
vgood      65
Name: decision, dtype: int64

In [20]:
df.replace(to_replace=["low","med","high","vhigh"], value=[1,2,3,4], inplace=True)

In [21]:
df

buyPrice  maintCost noDoors noPersons bootLuggage  safety decision
0           4          4       2         2       small       2    unacc
1           4          4       2         2       small       3    unacc
2           4          4       2         2           2       1    unacc
3           4          4       2         2           2       2    unacc
4           4          4       2         2           2       3    unacc
..        ...        ...     ...       ...         ...     ...      ...
426         1          1   5more      more           2       2     good
427         1          1   5more      more           2       3    vgood
428         1          1   5more      more         big       1    unacc
429         1          1   5more      more         big       2     good
430         1          1   5more      more         big       3    vgood

[1727 rows x 7 columns]

In [22]:
df.replace(to_replace=["small","big"], value=[1,3], inplace=True)

In [23]:
df

buyPrice  maintCost noDoors noPersons  bootLuggage  safety decision
0           4          4       2         2            1       2    unacc
1           4          4       2         2            1       3    unacc
2           4          4       2         2            2       1    unacc
3           4          4       2         2            2       2    unacc
4           4          4       2         2            2       3    unacc
..        ...        ...     ...       ...          ...     ...      ...
426         1          1   5more      more            2       2     good
427         1          1   5more      more            2       3    vgood
428         1          1   5more      more            3       1    unacc
429         1          1   5more      more            3       2     good
430         1          1   5more      more            3       3    vgood

[1727 rows x 7 columns]

In [24]:
df.replace(to_replace=["2","3","4","5more","more"], value=[2,3,4,5,5], inplace=True)

In [25]:
df

buyPrice  maintCost  noDoors  noPersons  bootLuggage  safety decision
0           4          4        2          2            1       2    unacc
1           4          4        2          2            1       3    unacc
2           4          4        2          2            2       1    unacc
3           4          4        2          2            2       2    unacc
4           4          4        2          2            2       3    unacc
..        ...        ...      ...        ...          ...     ...      ...
426         1          1        5          5            2       2     good
427         1          1        5          5            2       3    vgood
428         1          1        5          5            3       1    unacc
429         1          1        5          5            3       2     good
430         1          1        5          5            3       3    vgood

[1727 rows x 7 columns]

In [26]:
df.replace(to_replace=["unacc","acc","good","vgood"], value=[1,2,3,4], inplace=True)

In [27]:
df

buyPrice  maintCost  noDoors  noPersons  bootLuggage  safety  decision
0           4          4        2          2            1       2         1
1           4          4        2          2            1       3         1
2           4          4        2          2            2       1         1
3           4          4        2          2            2       2         1
4           4          4        2          2            2       3         1
..        ...        ...      ...        ...          ...     ...       ...
426         1          1        5          5            2       2         3
427         1          1        5          5            2       3         4
428         1          1        5          5            3       1         1
429         1          1        5          5            3       2         3
430         1          1        5          5            3       3         4

[1727 rows x 7 columns]

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1727 entries, 0 to 430
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   buyPrice     1727 non-null   int64
 1   maintCost    1727 non-null   int64
 2   noDoors      1727 non-null   int64
 3   noPersons    1727 non-null   int64
 4   bootLuggage  1727 non-null   int64
 5   safety       1727 non-null   int64
 6   decision     1727 non-null   int64
dtypes: int64(7)
memory usage: 107.9 KB


In [29]:
columns=['buyPrice', 'maintCost','noDoors','noPersons','bootLuggage','safety','decision']

for column in columns:
    df[column]=pd.to_numeric(df[column],downcast='integer')

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1727 entries, 0 to 430
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   buyPrice     1727 non-null   int8 
 1   maintCost    1727 non-null   int8 
 2   noDoors      1727 non-null   int8 
 3   noPersons    1727 non-null   int8 
 4   bootLuggage  1727 non-null   int8 
 5   safety       1727 non-null   int8 
 6   decision     1727 non-null   int8 
dtypes: int8(7)
memory usage: 25.3 KB


In [31]:
X = df.drop('decision',axis=1).values

In [32]:
y = df['decision'].values

In [33]:
print(X)

[[4 4 2 2 1 2]
 [4 4 2 2 1 3]
 [4 4 2 2 2 1]
 ...
 [1 1 5 5 3 1]
 [1 1 5 5 3 2]
 [1 1 5 5 3 3]]


In [34]:
print(y)

[1 1 1 ... 1 3 4]


In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

In [36]:
print (X_train.shape)
print (X_test.shape)

print (y_train.shape)
print (y_test.shape)

(1554, 6)
(173, 6)
(1554,)
(173,)


In [37]:
clf_entropy = DecisionTreeClassifier(criterion='entropy')

In [38]:
clf_entropy=clf_entropy.fit(X_train, y_train)

In [39]:
feature_name = df.columns[:-1]
target_name = df.columns[-1]

print(feature_name, '\n')
print(target_name)

Index(['buyPrice', 'maintCost', 'noDoors', 'noPersons', 'bootLuggage',
       'safety'],
      dtype='object') 

decision


In [45]:
class_names_str = [str(class_label) for class_label in clf_entropy.classes_]
feature_names = [f"feature_{i}" for i in range(X.shape[1])]  # Create generic feature names
dot_data = export_graphviz(clf_entropy, out_file=None, 
                           feature_names=feature_names,  
                           class_names=class_names_str,  # Convert class labels to strings
                           filled=True, rounded=True, special_characters=True)  
graph = graphviz.Source(dot_data)  
graph.render("decision_tree")


'decision_tree.pdf'

# Lab Logbook requirements. Answer the following questions and put in your lab logbook (Do not use more than 2 sentences for each question):


1.   What is the decision criterion at each node of the decision tree?
2.   How is entropy/gini index/loss change at each node?
3.   Is entropy decreasing or increasing in as we move down in tree?
4.   How many samples are left at each node? Can you see any pattern?
5.   What information is contained at leaf node?



In [ ]:
# Optional - The following is optional.

################################################################################
#
#
#Compare Decision tree performnce with SVM, KNN, and Logistic Regression.
# You can split your code into different cells according to your own choise
#
#
################################################################################